### ISSUE TITLE
You can just append `#readme` to links you want to focus on the heading of readme 

### ISSUE THREAD

**Issue by nikitavoloboev** [jorgegonzalez/essential-firefox#1]
You have many links like this in readme: 

https://github.com/honestbleeps/Reddit-Enhancement-Suite#reddit-enhancement-suite

This is bad because the heading might change at any time or if the heading adds some badge inline to the heading.

Instead you can do this:

https://github.com/honestbleeps/Reddit-Enhancement-Suite#readme

This will always work. Although personally I reference headings directly only if it links to some curated list that doesn't have any code, otherwise I don't do it.

**Comment by jorgegonzalez** [comment]
I didn't know this! Thanks, @nikitavoloboev
